# Generated by Django 4.1 on 2024-08-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sucursal",
            name="es_matriz",
            field=models.BooleanField(default=False),
        ),
    ]
