# Generated by Django 4.1 on 2024-08-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sucursal_es_matriz"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventario",
            unique_together={("producto", "sucursal")},
        ),
    ]
