# Generated by Django 4.1 on 2024-08-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_inventario_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="total_venta",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
