# Generated by Django 4.1 on 2024-08-19 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_empleado"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="empleado",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.empleado",
            ),
            preserve_default=False,
        ),
    ]
